spring.application.name=jobhunter

#config database
###
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/jobhunter
spring.datasource.username=root
spring.datasource.password=YOUR_DB_PASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
###
##config aws s3
spring.cloud.aws.credentials.access-key=YOUR_AWS_ACCESS_KEY
spring.cloud.aws.credentials.secret-key=YOUR_AWS_SECRET_KEY
spring.cloud.aws.region.static=ap-southeast-1
spring.cloud.aws.s3.bucket-name=my-jobhunter-app-bucket

#config upload file
###
# #default = 1MB
# spring.servlet.multipart.max-file-size=50MB

# #default = 10 MB (form data)
# spring.servlet.multipart.max-request-size=50MB
###

jwt.secret=YOUR_JWT_SECRET_KEY
#expiration time in milliseconds (1 day)
jwt.access-token-expiration=86400000
#refresh token expiration time in milliseconds (2 days)
jwt.refresh-expiration=604800000

app.upload.base-url=http://localhost:8080/uploads
app.upload.base-dir=uploads
app.upload.max-file-size=5242880
app.upload.allowed-file-types=jpg,jpeg,png,gif,webp
app.upload.allowed-folders=avatars,logos,images
app.seed-data=false
